Update build-and-push.yaml

diff --git a/.github/workflows/build-and-push.yaml b/.github/workflows/build-and-push.yaml
--- a/.github/workflows/build-and-push.yaml
+++ b/.github/workflows/build-and-push.yaml
@@ -1,4 +1,5 @@
-name: Train
+name: Train and Test
+
 on:
   pull_request:
     branches: [main]
@@ -8,7 +9,7 @@ on:
       - 'README.md'
 
 jobs:
-  build_and_push:
+  train:
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -30,3 +31,28 @@ jobs:
       
       - name: Push Docker image
         run: docker push dinkuma/assignments:latest
+
+  test:
+    runs-on: ubuntu-latest
+    needs: train
+    steps:
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Pull Docker image
+        run: docker pull dinkuma/assignments:latest
+
+      - name: Run Docker container
+        run: |
+          OUTPUT=$(docker run dinkuma/assignments:latest)
+          echo "Score:"
+          echo "$OUTPUT"
+          if [[ $(echo "$OUTPUT > 0.50" | bc -l) -eq 1 ]]; then
+            echo "Success - Score is greater than 0.50" 
+          else
+            echo "Failure - Score is not greater than 0.50"
+            exit 1
+          fi
